# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "luigi311/jellyplex-watched"
  amd64: "luigi311/jellyplex-watched"
  armhf: "luigi311/jellyplex-watched"
  armv7: "luigi311/jellyplex-watched"
  i386: "luigi311/jellyplex-watched"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: JellyPlex Watched"
  org.opencontainers.image.description: "A Home Assistant version of JellyPlex Watched."
  org.opencontainers.image.source: "https://github.com/georgeduckett/HomeAssistantAddons"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
