# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Jellyplex Watched
version: "sha-ef74802-slim"
slug: jellyplexwatched
description: JellyPlex-Watched add-on
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  DRYRUN: true
  DEBUG: false
  DEBUG_LEVEL: info
  SLEEP_DURATION: 3600
  GENERATE_GUIDS: false
  GENERATE_LOCATIONS: true
  PLEX_BASEURL: null
  PLEX_TOKEN: null
  JELLYFIN_BASEURL: null
  JELLYFIN_TOKEN: null
  USER_MAPPING: '{ "TomMiller": "tmiller7188" }'
  LIBRARY_MAPPING: '{ "Films": "Movies", "Shows": "TV Shows" }'
schema:
  DRYRUN: bool
  DEBUG: bool
  DEBUG_LEVEL: "list(info|debug)"
  SLEEP_DURATION: int(60,)
  GENERATE_GUIDS: bool
  GENERATE_LOCATIONS: bool
  PLEX_BASEURL: url?
  PLEX_TOKEN: str?
  JELLYFIN_BASEURL: url?
  JELLYFIN_TOKEN: str?
  USER_MAPPING: str?
  LIBRARY_MAPPING: str?
image: "luigi311/jellyplex-watched"
legacy: True
